export const mapping = {
    "あ": ["a"],
    "い": ["i", "yi"],
    "う": ["u", "wu", "whu"],
    "え": ["e"],
    "お": ["o"],
    "か": ["ka", "ca"],
    "き": ["ki"],
    "く": ["ku", "cu", "qu"],
    "け": ["ke"],
    "こ": ["ko", "co"],
    "さ": ["sa"],
    "し": ["si", "shi", "ci"],
    "す": ["su"],
    "せ": ["se", "ce"],
    "そ": ["so"],
    "た": ["ta"],
    "ち": ["ti", "chi"],
    "つ": ["tu", "tsu"],
    "て": ["te"],
    "と": ["to"],
    "な": ["na"],
    "に": ["ni"],
    "ぬ": ["nu"],
    "ね": ["ne"],
    "の": ["no"],
    "は": ["ha"],
    "ひ": ["hi"],
    "ふ": ["hu", "fu"],
    "へ": ["he"],
    "ほ": ["ho"],
    "ま": ["ma"],
    "み": ["mi"],
    "む": ["mu"],
    "め": ["me"],
    "も": ["mo"],
    "や": ["ya"],
    "ゆ": ["yu"],
    "よ": ["yo"],
    "ら": ["ra"],
    "り": ["ri"],
    "る": ["ru"],
    "れ": ["re"],
    "ろ": ["ro"],
    "わ": ["wa"],
    "を": ["wo"],
    "ん": ["nn", "n", "xn"],
    "が": ["ga"],
    "ぎ": ["gi"],
    "ぐ": ["gu"],
    "げ": ["ge"],
    "ご": ["go"],
    "ざ": ["za"],
    "じ": ["ji", "zi"],
    "ず": ["zu"],
    "ぜ": ["ze"],
    "ぞ": ["zo"],
    "だ": ["da"],
    "ぢ": ["di"],
    "づ": ["du"],
    "で": ["de"],
    "ど": ["do"],
    "ば": ["ba"],
    "び": ["bi"],
    "ぶ": ["bu"],
    "べ": ["be"],
    "ぼ": ["bo"],
    "ぱ": ["pa"],
    "ぴ": ["pi"],
    "ぷ": ["pu"],
    "ぺ": ["pe"],
    "ぽ": ["po"],
    "ぁ": ["la", "xa"],
    "ぃ": ["li", "xi", "lyi", "xyi"],
    "ぅ": ["lu", "xu"],
    "ぇ": ["le", "xe", "lye", "xye"],
    "ぉ": ["lo", "xo"],
    "ゃ": ["lya", "xya"],
    "ゅ": ["lyu", "xyu"],
    "ょ": ["lyo", "xyo"],
    "っ": ["ltu", "ltsu", "xtu", "xtsu"],
    "きゃ": ["kya", "kilya", "kixya"],
    "きぃ": ["kyi", "kili", "kilyi", "kixi", "kixyi"],
    "きゅ": ["kyu", "kilyu", "kixyu"],
    "きぇ": ["kye", "kile", "kilye", "kixe", "kixye"],
    "きょ": ["kyo", "kilyo", "kixyo"],
    "ぎゃ": ["gya", "gilya", "gixya"],
    "ぎぃ": ["gyi", "gili", "gilyi", "gixi", "gixyi"],
    "ぎゅ": ["gyu", "gilyu", "gixyu"],
    "ぎぇ": ["gye", "gile", "gilye", "gixe", "gixye"],
    "ぎょ": ["gyo", "gilyo", "gixyo"],
    "くぁ": ["qa", "kwa", "kula", "kuxa", "cula", "cuxa", "qula", "quxa"],
    "くぃ": ["qi", "qyi", "kuli", "kuxi", "kulyi", "kuxyi", "culi", "culyi", "cuxi", "cuxyi", "quli", "quxi", "qulyi", "quxyi"],
    "くぅ": ["qwu", "kulu", "kuxu", "culu", "cuxu", "qulu", "quxu"],
    "くぇ": ["qe", "qwe", "kule", "kuxe", "kulye", "kuxye", "cule", "cuxe", "culye", "cuxye", "qule", "quxe", "qulye", "quxye"],
    "くぉ": ["qo", "qwo", "kulo", "kuxo", "culo", "cuxo", "qulo", "quxo"],
    "ぐぁ": ["gwa", "gula", "guxa"],
    "ぐぃ": ["gwi", "guli", "gulyi", "guxi", "guxyi"],
    "ぐぅ": ["gwu", "gulu", "guxu"],
    "ぐぇ": ["gwe", "gule", "guxe", "gulye", "guxye"],
    "ぐぉ": ["gwo", "gulo", "guxo"],
    "しゃ": ["sya", "sha", "silya", "sixya", "shilya", "shixya", "cilya", "cixya"],
    "しぃ": ["syi", "sili", "sixi", "silyi", "sixyi", "shili", "shixi", "shilyi", "shixyi", "cili", "cixi", "cilyi", "cixyi"],
    "しゅ": ["syu", "shu", "silyu", "sixyu", "shilyu", "shixyu", "cilyu", "cixyu"],
    "しぇ": ["sye", "she", "sile", "silye", "sixe", "sixye", "shile", "shilye", "shixe", "shixye", "cile", "cilye", "cixe", "cixye"],
    "しょ": ["syo", "sho", "silyo", "sixyo", "shilyo", "shixyo", "cilyo", "cixyo"],
    "じゃ": ["ja", "jya", "zya", "jilya", "jixya", "zilya", "zixya"],
    "じぃ": ["jyi", "zyi", "jili", "jixi", "jilyi", "jixyi", "zili", "zixi", "zilyi", "zixyi"],
    "じゅ": ["ju", "jyu", "zyu", "jilyu", "jixyu", "zilyu", "zixyu"],
    "じぇ": ["je", "jye", "zye", "jile", "jixe", "jilye", "jixye", "zile", "zixe", "zilye", "zixye"],
    "じょ": ["jo", "jyo", "zyo", "jilyo", "jixyo", "zilyo", "zixyo"],
    "すぁ": ["swa", "sula", "suxa"],
    "すぃ": ["swi", "suli", "sulyi", "suxi", "suxyi"],
    "すぅ": ["swu", "sulu", "suxu"],
    "すぇ": ["swe", "sule", "suxe", "sulye", "suxye"],
    "すぉ": ["swo", "sulo", "suxo"],
    "ちゃ": ["tya", "cha", "cya", "tilya", "tixya", "chilya", "chixya"],
    "ちぃ": ["tyi", "cyi", "tili", "tixi", "tilyi", "tixyi", "chili", "chixi", "chilyi", "chixyi"],
    "ちゅ": ["tyu", "chu", "cyu", "tilyu", "tixyu", "chilyu", "chixyu"],
    "ちぇ": ["tye", "che", "cye", "tile", "tixe", "tilye", "tixye", "chile", "chixe", "chilye", "chixye"],
    "ちょ": ["tyo", "cho", "cyo", "tilyo", "tixyo", "chilyo", "chixyo"],
    "ぢゃ": ["dya", "dilya", "dixya"],
    "ぢゅ": ["dyu", "dilyu", "dixyu"],
    "ぢぇ": ["dye", "dile", "dixe", "dilye", "dixye"],
    "ぢょ": ["dyo", "dilyo", "dixyo"],
    "つぁ": ["tsa", "tula", "tuxa", "tsula", "tsuxa"],
    "つぃ": ["tsi", "tuli", "tuxi", "tulyi", "tuxyi", "tsuli", "tsuxi", "tsulyi", "tsuxyi"],
    "つぇ": ["tse", "tule", "tuxe", "tulye", "tuxye", "tsule", "tsuxe", "tsulye", "tsuxye"],
    "つぉ": ["tso", "tulo", "tuxo", "tsulo", "tsuxo"],
    "てゃ": ["tha", "telya", "texya"],
    "てぃ": ["thi", "teli", "texi", "telyi", "texyi"],
    "てゅ": ["thu", "telyu", "texyu"],
    "てぇ": ["the", "tele", "texe", "telye", "texye"],
    "てょ": ["tho", "telyo", "texyo"],
    "でゃ": ["dha", "delya", "dexya"],
    "でぃ": ["dhi", "deli", "dexi", "delyi", "dexyi"],
    "でゅ": ["dhu", "delyu", "dexyu"],
    "でぇ": ["dhe", "dele", "dexe", "delye", "dexye"],
    "でょ": ["dho", "delyo", "dexyo"],
    "とぁ": ["twa", "tola", "toxa"],
    "とぃ": ["twi", "toli", "toxi", "tolyi", "toxyi"],
    "とぅ": ["twu", "tolu", "toxu"],
    "とぇ": ["twe", "tole", "toxe", "tolye", "toxye"],
    "とぉ": ["two", "tolo", "toxo"],
    "どぁ": ["dwa", "dola", "doxa"],
    "どぃ": ["dwi", "doli", "doxi", "dolyi", "doxyi"],
    "どぅ": ["dwu", "dolu", "doxu"],
    "どぇ": ["dwe", "dole", "doxe", "dolye", "doxye"],
    "どぉ": ["dwo", "dolo", "doxo"],
    "にゃ": ["nya", "nilya", "nixya"],
    "にぃ": ["nyi", "nili", "nixi", "nilyi", "nixyi"],
    "にゅ": ["nyu", "nilyu", "nixyu"],
    "にぇ": ["nye", "nile", "nixe", "nilye", "nixye"],
    "にょ": ["nyo", "nilyo", "nixyo"],
    "ぴゃ": ["pya", "pilya", "pixya"],
    "ぴぃ": ["pyi", "pili", "pixi", "pilyi", "pixyi"],
    "ぴゅ": ["pyu", "pilyu", "pixyu"],
    "ぴぇ": ["pye", "pile", "pixe", "pilye", "pixye"],
    "ぴょ": ["pyo", "pilyo", "pixyo"],
    "ひゃ": ["hya", "hilya", "hixya"],
    "ひぃ": ["hyi", "hili", "hixi", "hilyi", "hixyi"],
    "ひゅ": ["hyu", "hilyu", "hixyu"],
    "ひぇ": ["hye", "hile", "hixe", "hilye", "hixye"],
    "ひょ": ["hyo", "hilyo", "hixyo"],
    "びゃ": ["bya", "bilya", "bixya"],
    "びぃ": ["byi", "bili", "bixi", "bilyi", "bixyi"],
    "びゅ": ["byu", "bilyu", "bixyu"],
    "びぇ": ["bye", "bile", "bixe", "bilye", "bixye"],
    "びょ": ["byo", "bilyo", "bixyo"],
    "ふゃ": ["fya", "fulya", "fuxya", "hulya", "huxya"],
    "ふぃ": ["fi", "fyi", "fuli", "fuxi", "fulyi", "fuxyi", "huli", "huxi", "hulyi", "huxyi"],
    "ふゅ": ["fyu", "fulyu", "fuxyu", "hulyu", "huxyu"],
    "ふぇ": ["fe", "fye", "fule", "fuxe", "fulye", "fuxye", "hule", "huxe", "hulye", "huxye"],
    "ふょ": ["fyo", "fulyo", "fuxyo", "hulyo", "huxyo"],
    "ふぁ": ["fa", "fula", "fuxa", "hula", "huxa"],
    "ふぉ": ["fo", "fulo", "fuxo", "hulo", "huxo"],
    "みゃ": ["mya", "milya", "mixya"],
    "みぃ": ["myi", "mili", "mixi", "milyi", "mixyi"],
    "みゅ": ["myu", "milyu", "mixyu"],
    "みぇ": ["mye", "mile", "mixe", "milye", "mixye"],
    "みょ": ["myo", "milyo", "mixyo"],
    "りゃ": ["rya", "rilya", "rixya"],
    "りぃ": ["ryi", "rili", "rixi", "rilyi", "rixyi"],
    "りゅ": ["ryu", "rilyu", "rixyu"],
    "りぇ": ["rye", "rile", "rixe", "rilye", "rixye"],
    "りょ": ["ryo", "rilyo", "rixyo"],
    "うぁ": ["wha", "ula", "uxa", "wula", "wuxa", "whula", "whuxa"],
    "うぃ": ["wi", "whi", "uli", "uxi", "ulyi", "uxyi", "wuli", "wuxi", "wulyi", "wuxyi", "whuli"],
    "うぇ": ["we", "whe", "ule", "uxe", "ulye", "uxye", "wule", "wuxe", "wulye", "wuxye", "whule", "whuxe", "whulye", "whuxye"],
    "うぉ": ["who", "ulo", "uxo", "wulo", "wuxo", "whulo", "whuxo"],
    "ゔぁ": ["va", "vula", "vuxa"],
    "ゔぃ": ["vi", "vyi", "vuli", "vuxi", "vulyi", "vuxyi"],
    "ゔ": ["vu"],
    "ゔぇ": ["ve", "vye", "vule", "vuxe", "vulye", "vuxye"],
    "ゔぉ": ["vo", "vulo", "vuxo"],
    "ゔゃ": ["vya", "vulya", "vuxya"],
    "ゔゅ": ["vyu", "vulyu", "vuxyu"],
    "ゔょ": ["vyo", "vulyo", "vuxyo"],
    "ゐ": ["wyi"],
    "ゑ": ["wye"],
    "んあ": ["nna", "xna"],
    "んい": ["nni", "xni", "nnyi", "xnyi"],
    "んう": ["nnu", "xnu", "nnwu", "xnwu", "nnwhu", "xnwhu"],
    "んえ": ["nne", "xne"],
    "んお": ["nno", "xno"],
    "んか": ["nka", "nca", "nnka", "nnca", "xnka", "xnca"],
    "んき": ["nki", "nnki", "xnki"],
    "んく": ["nku", "ncu", "nqu", "nnku", "nncu", "nnqu", "xnku", "xncu", "xnqu"],
    "んけ": ["nke", "nnke", "xnke"],
    "んこ": ["nko", "nco", "nnko", "nnco", "xnko", "xnco"],
    "んさ": ["nsa", "nnsa", "xnsa"],
    "んし": ["nsi", "nshi", "nci", "nnsi", "nnshi", "nnci", "xnsi", "xnshi", "xnci"],
    "んす": ["nsu", "nnsu", "xnsu"],
    "んせ": ["nse", "nce", "nnse", "nnce", "xnse", "xnce"],
    "んそ": ["nso", "nnso", "xnso"],
    "んた": ["nta", "nnta", "xnta"],
    "んち": ["nti", "nchi", "nnti", "nnchi", "xnti", "xnchi"],
    "んつ": ["ntu", "ntsu", "nntu", "nntsu", "xntu", "xntsu"],
    "んて": ["nte", "nnte", "xnte"],
    "んと": ["nto", "nnto", "xnto"],
    "んな": ["nnna", "xnna"],
    "んに": ["nnni", "xnni"],
    "んぬ": ["nnnu", "xnnu"],
    "んね": ["nnne", "xnne"],
    "んの": ["nnno", "xnno"],
    "んは": ["nha", "nnha", "xnha"],
    "んひ": ["nhi", "nnhi", "xnhi"],
    "んふ": ["nfu", "nhu", "nnfu", "nnhu", "xnfu", "xnhu"],
    "んへ": ["nhe", "nnhe", "xnhe"],
    "んほ": ["nho", "nnho", "xnho"],
    "んま": ["nma", "nnma", "xnma"],
    "んみ": ["nmi", "nnmi", "xnmi"],
    "んむ": ["nmu", "nnmu", "xnmu"],
    "んめ": ["nme", "nnme", "xnme"],
    "んも": ["nmo", "nnmo", "xnmo"],
    "んや": ["nnya", "xnya"],
    "んゆ": ["nnyu", "xnyu"],
    "んよ": ["nnyo", "xnyo"],
    "んら": ["nra", "nnra", "xnra"],
    "んり": ["nri", "nnri", "xnri"],
    "んる": ["nru", "nnru", "xnru"],
    "んれ": ["nre", "nnre", "xnre"],
    "んろ": ["nro", "nnro", "xnro"],
    "んわ": ["nwa", "nnwa", "xnwa"],
    "んを": ["nwo", "nnwo", "xnwo"],
    "んが": ["nga", "nnga", "xnga"],
    "んぎ": ["ngi", "nngi", "xngi"],
    "んぐ": ["ngu", "nngu", "xngu"],
    "んげ": ["nge", "nnge", "xnge"],
    "んご": ["ngo", "nngo", "xngo"],
    "んざ": ["nza", "nnza", "xnza"],
    "んじ": ["nji", "nzi", "nnji", "nnzi", "xnji", "xnzi"],
    "んず": ["nzu", "nnzu", "xnzu"],
    "んぜ": ["nze", "nnze", "xnze"],
    "んぞ": ["nzo", "nnzo", "xnze"],
    "んだ": ["nda", "nnda", "xnda"],
    "んぢ": ["ndi", "nndi", "xndi"],
    "んづ": ["ndu", "nndu", "xndu"],
    "んで": ["nde", "nnde", "xnde"],
    "んど": ["ndo", "nndo", "xndo"],
    "んば": ["nba", "nnba", "xnba"],
    "んび": ["nbi", "nnbi", "xnbi"],
    "んぶ": ["nbu", "nnbu", "xnbu"],
    "んべ": ["nbe", "nnbe", "xnbe"],
    "んぼ": ["nbo", "nnbo", "xnbo"],
    "んぱ": ["npa", "nnpa", "xnpa"],
    "んぴ": ["npi", "nnpi", "xnpi"],
    "んぷ": ["npu", "nnpu", "xnpu"],
    "んぺ": ["npe", "nnpe", "xnpe"],
    "んぽ": ["npo", "nnpo", "xnpo"],
    "んきゃ": ["nkya", "nkilya", "nkixya", "nnkya", "nnkilya", "nnkixya", "xnkya", "xnkilya", "xnkixya"],
    "んきぃ": ["nkyi", "nkili", "nkilyi", "nkixi", "nkixyi", "nnkyi", "nnkili", "nnkilyi", "nnkixi", "nnkixyi", "xnkyi", "xnkili", "xnkilyi", "xnkixi", "xnkixyi"],
    "んきゅ": ["nkyu", "nkilyu", "nkixyu", "nnkyu", "nnkilyu", "nnkixyu", "xnkyu", "xnkilyu", "xnkixyu"],
    "んきぇ": ["nkye", "nkile", "nkilye", "nkixe", "nkixye", "nnkye", "nnkile", "nnkilye", "nnkixe", "nnkixye", "xnkye", "xnkile", "xnkilye", "xnkixe", "xnkixye"],
    "んきょ": ["nkyo", "nkilyo", "nkixyo", "nnkyo", "nnkilyo", "nnkixyo", "xnkyo", "xnkilyo", "xnkixyo"],
    "んぎゃ": ["ngya", "ngilya", "ngixya", "nngya", "nngilya", "nngixya", "xngya", "xngilya", "xngixya"],
    "んぎぃ": ["ngyi", "ngili", "ngilyi", "ngixi", "ngixyi", "nngyi", "nngili", "nngilyi", "nngixi", "nngixyi", "xngyi", "xngili", "xngilyi", "xngixi", "xngixyi"],
    "んぎゅ": ["ngyu", "ngilyu", "ngixyu", "nngyu", "nngilyu", "nngixyu", "xngyu", "xngilyu", "xngixyu"],
    "んぎぇ": ["ngye", "ngile", "ngilye", "ngixe", "ngixye", "nngye", "nngile", "nngilye", "nngixe", "nngixye", "xngye", "xngile", "xngilye", "xngixe", "xngixye"],
    "んぎょ": ["ngyo", "ngilyo", "ngixyo", "nngyo", "nngilyo", "nngixyo", "xngyo", "xngilyo", "xngixyo"],
    "んしゃ": ["nsya", "nsha", "nsilya", "nsixya", "nshilya", "nshixya", "ncilya", "ncixya", "nnsya", "nnsha", "nnsilya", "nnsixya", "nnshilya", "nnshixya", "nncilya", "nncixya", "xnsya", "xnsha", "xnsilya", "xnsixya", "xnshilya", "xnshixya", "xncilya", "xncixya"],
    "んしぃ": ["nsyi", "nsili", "nsixi", "nsilyi", "nsixyi", "nshili", "nshixi", "nshilyi", "nshixyi", "ncili", "ncixi", "ncilyi", "ncixyi", "nnsyi", "nnsili", "nnsixi", "nnsilyi", "nnsixyi", "nnshili", "nnshixi", "nnshilyi", "nnshixyi", "nncili", "nncixi", "nncilyi", "nncixyi", "xnsyi", "xnsili", "xnsixi", "xnsilyi", "xnsixyi", "xnshili", "xnshixi", "xnshilyi", "xnshixyi", "xncili", "xncixi", "xncilyi", "xncixyi"],
    "んしゅ": ["nsyu", "nshu", "nsilyu", "nsixyu", "nshilyu", "nshixyu", "ncilyu", "ncixyu", "nnsyu", "nnshu", "nnsilyu", "nnsixyu", "nnshilyu", "nnshixyu", "nncilyu", "nncixyu", "xnsyu", "xnshu", "xnsilyu", "xnsixyu", "xnshilyu", "xnshixyu", "xncilyu", "xncixyu"],
    "んしぇ": ["nsye", "nshe", "nsile", "nsilye", "nsixe", "nsixye", "nshile", "nshilye", "nshixe", "nshixye", "ncile", "ncilye", "ncixe", "ncixye", "nnsye", "nnshe", "nnsile", "nnsilye", "nnsixe", "nnsixye", "nnshile", "nnshilye", "nnshixe", "nnshixye", "nncile", "nncilye", "nncixe", "nncixye", "xnsye", "xnshe", "xnsile", "xnsilye", "xnsixe", "xnsixye", "xnshile", "xnshilye", "xnshixe", "xnshixye", "xncile", "xncilye", "xncixe", "xncixye"],
    "んしょ": ["nsyo", "nsho", "nsilyo", "nsixyo", "nshilyo", "nshixyo", "ncilyo", "ncixyo", "nnsyo", "nnsho", "nnsilyo", "nnsixyo", "nnshilyo", "nnshixyo", "nncilyo", "nncixyo", "xnsyo", "xnsho", "xnsilyo", "xnsixyo", "xnshilyo", "xnshixyo", "xncilyo", "xncixyo"],
    "んじゃ": ["nja", "njya", "nzya", "njilya", "njixya", "nzilya", "nzixya", "nnja", "nnjya", "nnzya", "nnjilya", "nnjixya", "nnzilya", "nnzixya", "xnja", "xnjya", "xnzya", "xnjilya", "xnjixya", "xnzilya", "xnzixya"],
    "んじぃ": ["njyi", "nzyi", "njili", "njixi", "njilyi", "njixyi", "nzili", "nzixi", "nzilyi", "nzixyi", "nnjyi", "nnzyi", "nnjili", "nnjixi", "nnjilyi", "nnjixyi", "nnzili", "nnzixi", "nnzilyi", "nnzixyi", "xnjyi", "xnzyi", "xnjili", "xnjixi", "xnjilyi", "xnjixyi", "xnzili", "xnzixi", "xnzilyi", "xnzixyi"],
    "んじゅ": ["nju", "njyu", "nzyu", "njilyu", "njixyu", "nzilyu", "nzixyu", "nnju", "nnjyu", "nnzyu", "nnjilyu", "nnjixyu", "nnzilyu", "nnzixyu", "xnju", "xnjyu", "xnzyu", "xnjilyu", "xnjixyu", "xnzilyu", "xnzixyu"],
    "んじぇ": ["nje", "njye", "nzye", "njile", "njixe", "njilye", "njixye", "nzile", "nzixe", "nzilye", "nzixye", "nnje", "nnjye", "nnzye", "nnjile", "nnjixe", "nnjilye", "nnjixye", "nnzile", "nnzixe", "nnzilye", "nnzixye", "xnje", "xnjye", "xnzye", "xnjile", "xnjixe", "xnjilye", "xnjixye", "xnzile", "xnzixe", "xnzilye", "xnzixye"],
    "んじょ": ["njo", "njyo", "nzyo", "njilyo", "njixyo", "nzilyo", "nzixyo", "nnjo", "nnjyo", "nnzyo", "nnjilyo", "nnjixyo", "nnzilyo", "nnzixyo", "xnjo", "xnjyo", "xnzyo", "xnjilyo", "xnjixyo", "xnzilyo", "xnzixyo"],
    "んちゃ": ["ntya", "ncha", "ncya", "ntilya", "ntixya", "nchilya", "nchixya", "nntya", "nncha", "nncya", "nntilya", "nntixya", "nnchilya", "nnchixya", "xntya", "xncha", "xncya", "xntilya", "xntixya", "xnchilya", "xnchixya"],
    "んちぃ": ["ntyi", "ncyi", "ntili", "ntixi", "ntilyi", "ntixyi", "nchili", "nchixi", "nchilyi", "nchixyi", "nntyi", "nncyi", "nntili", "nntixi", "nntilyi", "nntixyi", "nnchili", "nnchixi", "nnchilyi", "nnchixyi", "xntyi", "xncyi", "xntili", "xntixi", "xntilyi", "xntixyi", "xnchili", "xnchixi", "xnchilyi", "xnchixyi"],
    "んちゅ": ["ntyu", "nchu", "ncyu", "ntilyu", "ntixyu", "nchilyu", "nchixyu", "nntyu", "nnchu", "nncyu", "nntilyu", "nntixyu", "nnchilyu", "nnchixyu", "xntyu", "xnchu", "xncyu", "xntilyu", "xntixyu", "xnchilyu", "xnchixyu"],
    "んちぇ": ["ntye", "nche", "ncye", "ntile", "ntixe", "ntilye", "ntixye", "nchile", "nchixe", "nchilye", "nchixye", "nntye", "nnche", "nncye", "nntile", "nntixe", "nntilye", "nntixye", "nnchile", "nnchixe", "nnhilye", "nnchixye", "xntye", "xnche", "xncye", "xntile", "xntixe", "xntilye", "xntixye", "xnchile", "xnchixe", "xnchilye", "xnchixye"],
    "んちょ": ["ntyo", "ncho", "ncyo", "ntilyo", "ntixyo", "nchilyo", "nchixyo", "nntyo", "nncho", "nncyo", "nntilyo", "nntixyo", "nnchilyo", "nnchixyo", "xntyo", "xncho", "xncyo", "xntilyo", "xntixyo", "xnchilyo", "xnchixyo"],
    "んぢゃ": ["ndya", "ndilya", "ndixya", "nndya", "nndilya", "nndixya", "xndya", "xndilya", "xndixya"],
    "んぢゅ": ["ndyu", "ndilyu", "ndixyu", "nndyu", "nndilyu", "nndixyu", "xndyu", "xndilyu", "xndixyu"],
    "んぢぇ": ["ndye", "ndile", "ndixe", "ndilye", "ndixye", "nndye", "nndile", "nndixe", "nndilye", "nndixye","xndye", "xndile", "xndixe", "xndilye", "xndixye"],
    "んぢょ": ["ndyo", "ndilyo", "ndixyo", "nndyo", "nndilyo", "nndixyo", "xndyo", "xndilyo", "xndixyo"],
    "んつぁ": ["ntsa", "ntula", "ntuxa", "ntsula", "ntsuxa", "nntsa", "nntula", "nntuxa", "nntsula", "nntsuxa", "xntsa", "xntula", "xntuxa", "xntsula", "xntsuxa"],
    "んつぃ": ["ntsi", "ntuli", "ntuxi", "ntulyi", "ntuxyi", "ntsuli", "ntsuxi", "ntsulyi", "ntsuxyi", "nntsi", "nntuli", "nntuxi", "nntulyi", "nntuxyi", "nntsuli", "nntsuxi", "nntsulyi", "nntsuxyi", "xntsi", "xntuli", "xntuxi", "xntulyi", "xntuxyi", "xntsuli", "xntsuxi", "xntsulyi", "xntsuxyi"],
    "んつぇ": ["ntse", "ntule", "ntuxe", "ntulye", "ntuxye", "ntsule", "ntsuxe", "ntsulye", "ntsuxye", "nntse", "nntule", "nntuxe", "nntulye", "nntuxye", "nntsule", "nntsuxe", "nntsulye", "nntsuxye", "xntse", "xntule", "xntuxe", "xntulye", "xntuxye", "xntsule", "xntsuxe", "xntsulye", "xntsuxye"],
    "んつぉ": ["ntso", "ntulo", "ntuxo", "ntsulo", "ntsuxo", "nntso", "nntulo", "nntuxo", "nntsulo", "nntsuxo", "xntso", "xntulo", "xntuxo", "xntsulo", "xntsuxo"],
    "んてゃ": ["ntha", "ntelya", "ntexya", "nntha", "nntelya", "nntexya", "xntha", "xntelya", "xntexya"],
    "んてぃ": ["nthi", "nteli", "ntexi", "ntelyi", "ntexyi", "nnthi", "nnteli", "nntexi", "nntelyi", "nntexyi", "xnthi", "xnteli", "xntexi", "xntelyi", "xntexyi"],
    "んてゅ": ["nthu", "ntelyu", "ntexyu", "nnthu", "nntelyu", "nntexyu", "xnthu", "xntelyu", "xntexyu"],
    "んてぇ": ["nthe", "ntele", "ntexe", "ntelye", "ntexye", "nnthe", "nntele", "nntexe", "nntelye", "nntexye", "xnthe", "xntele", "xntexe", "xntelye", "xntexye"],
    "んてょ": ["ntho", "ntelyo", "ntexyo", "nntho", "nntelyo", "nntexyo", "xntho", "xntelyo", "xntexyo"],
    "んでゃ": ["ndha", "ndelya", "ndexya", "nndha", "nndelya", "nndexya", "xndha", "xndelya", "xndexya"],
    "んでぃ": ["ndhi", "ndeli", "ndexi", "ndelyi", "ndexyi", "nndhi", "nndeli", "nndexi", "nndelyi", "nndexyi", "xndhi", "xndeli", "xndexi", "xndelyi", "xndexyi"],
    "んでゅ": ["ndhu", "ndelyu", "ndexyu", "nndhu", "nndelyu", "nndexyu", "xndhu", "xndelyu", "xndexyu"],
    "んでぇ": ["ndhe", "ndele", "ndexe", "ndelye", "ndexye", "nndhe", "nndele", "nndexe", "nndelye", "nndexye", "xndhe", "xndele", "xndexe", "xndelye", "xndexye"],
    "んでょ": ["ndho", "ndelyo", "ndexyo", "nndho", "nndelyo", "nndexyo", "xndho", "xndelyo", "xndexyo"],
    "んとぁ": ["ntwa", "ntola", "ntoxa", "nntwa", "nntola", "nntoxa", "xntwa", "xntola", "xntoxa"],
    "んとぃ": ["ntwi", "ntoli", "ntoxi", "ntolyi", "ntoxyi", "nntwi", "nntoli", "nntoxi", "nntolyi", "nntoxyi", "xntwi", "xntoli", "xntoxi", "xntolyi", "xntoxyi"],
    "んとぅ": ["ntwu", "ntolu", "ntoxu", "nntwu", "nntolu", "nntoxu", "xntwu", "xntolu", "xntoxu"],
    "んとぇ": ["ntwe", "ntole", "ntoxe", "ntolye", "ntoxye", "nntwe", "nntole", "nntoxe", "nntolye", "nntoxye", "xntwe", "xntole", "xntoxe", "xntolye", "xntoxye"],
    "んとぉ": ["ntwo", "ntolo", "ntoxo", "nntwo", "nntolo", "nntoxo", "xntwo", "xntolo", "xntoxo"],
    "んどぁ": ["ndwa", "ndola", "ndoxa", "nndwa", "nndola", "nndoxa", "xndwa", "xndola", "xndoxa"],
    "んどぃ": ["ndwi", "ndoli", "ndoxi", "ndolyi", "ndoxyi", "nndwi", "nndoli", "nndoxi", "nndolyi", "nndoxyi", "xndwi", "xndoli", "xndoxi", "xndolyi", "xndoxyi"],
    "んどぅ": ["ndwu", "ndolu", "ndoxu", "nndwu", "nndolu", "nndoxu", "xndwu", "xndolu", "xndoxu"],
    "んどぇ": ["ndwe", "ndole", "ndoxe", "ndolye", "ndoxye", "nndwe", "nndole", "nndoxe", "nndolye", "nndoxye", "xndwe", "xndole", "xndoxe", "xndolye", "xndoxye"],
    "んどぉ": ["ndwo", "ndolo", "ndoxo", "nndwo", "nndolo", "nndoxo", "xndwo", "xndolo", "xndoxo"],
    "んにゃ": ["nnnya", "xnnya", "nnnixya", "xnnixya", "nnnilya", "xnnilya"],
    "んにゅ": ["nnnyu", "xnnyu", "nnnixyu", "xnnixyu", "nnnilyu", "xnnilyu"],
    "んにょ": ["nnnyo", "xnnyo", "nnnixyo", "xnnixyo", "nnnilyo", "xnnilyo"],
    "んぴゃ": ["npya", "npilya", "npixya", "nnpya", "nnpilya", "nnpixya", "xnpya", "xnpilya", "xnpixya"],
    "んぴぃ": ["npyi", "npili", "npixi", "npilyi", "npixyi", "nnpyi", "nnpili", "nnpixi", "nnpilyi", "nnpixyi", "xnpyi", "xnpili", "xnpixi", "xnpilyi", "xnpixyi"],
    "んぴゅ": ["npyu", "npilyu", "npixyu", "nnpyu", "nnpilyu", "nnpixyu", "xnpyu", "xnpilyu", "xnpixyu"],
    "んぴぇ": ["npye", "npile", "npixe", "npilye", "npixye", "nnpye", "nnpile", "nnpixe", "nnpilye", "nnpixye", "xnpye", "xnpile", "xnpixe", "xnpilye", "xnpixye"],
    "んぴょ": ["npyo", "npilyo", "npixyo", "nnpyo", "nnpilyo", "nnpixyo", "xnpyo", "xnpilyo", "xnpixyo"],
    "んひゃ": ["nhya", "nhilya", "nhixya", "nnhya", "nnhilya", "nnhixya", "xnhya", "xnhilya", "xnhixya"],
    "んひぃ": ["nhyi", "nhili", "nhixi", "nhilyi", "nhixyi", "nnhyi", "nnhili", "nnhixi", "nnhilyi", "nnhixyi", "xnhyi", "xnhili", "xnhixi", "xnhilyi", "xnhixyi"],
    "んひゅ": ["nhyu", "nhilyu", "nhixyu", "nnhyu", "nnhilyu", "nnhixyu", "xnhyu", "xnhilyu", "xnhixyu"],
    "んひぇ": ["nhye", "nhile", "nhixe", "nhilye", "nhixye", "nnhye", "nnhile", "nnhixe", "nnhilye", "nnhixye", "xnhye", "xnhile", "xnhixe", "xnhilye", "xnhixye"],
    "んひょ": ["nhyo", "nhilyo", "nhixyo", "nnhyo", "nnhilyo", "nnhixyo", "xnhyo", "xnhilyo", "xnhixyo"],
    "んびゃ": ["nbya", "nbilya", "nbixya", "nnbya", "nnbilya", "nnbixya", "xnbya", "xnbilya", "xnbixya"],
    "んびぃ": ["nbyi", "nbili", "nbixi", "nbilyi", "nbixyi", "nnbyi", "nnbili", "nnbixi", "nnbilyi", "nnbixyi", "xnbyi", "xnbili", "xnbixi", "xnbilyi", "xnbixyi"],
    "んびゅ": ["nbyu", "nbilyu", "nbixyu", "nnbyu", "nnbilyu", "nnbixyu", "xnbyu", "xnbilyu", "xnbixyu"],
    "んびぇ": ["nbye", "nbile", "nbixe", "nbilye", "nbixye", "nnbye", "nnbile", "nnbixe", "nnbilye", "nnbixye", "xnbye", "xnbile", "xnbixe", "xnbilye", "xnbixye"],
    "んびょ": ["nbyo", "nbilyo", "nbixyo", "nnbyo", "nnbilyo", "nnbixyo", "xnbyo", "xnbilyo", "xnbixyo"],
    "んふゃ": ["nfya", "nfulya", "nfuxya", "nhulya", "nhuxya", "nnfya", "nnfulya", "nnfuxya", "nnhulya", "nnhuxya", "xnfya", "xnfulya", "xnfuxya", "xnhulya", "xnhuxya"],
    "んふぃ": ["nfi", "nfyi", "nfuli", "nfuxi", "nfulyi", "nfuxyi", "nhuli", "nhuxi", "nhulyi", "nhuxyi", "nnfi", "nnfyi", "nnfuli", "nnfuxi", "nnfulyi", "nnfuxyi", "nnhuli", "nnhuxi", "nnhulyi", "nnhuxyi", "xnfi", "xnfyi", "xnfuli", "xnfuxi", "xnfulyi", "xnfuxyi", "xnhuli", "xnhuxi", "xnhulyi", "xnhuxyi"],
    "んふゅ": ["nfyu", "nfulyu", "nfuxyu", "nhulyu", "nhuxyu", "nnfyu", "nnfulyu", "nnfuxyu", "nnhulyu", "nnhuxyu", "xnfyu", "xnfulyu", "xnfuxyu", "xnhulyu", "xnhuxyu"],
    "んふぇ": ["nfe", "nfye", "nfule", "nfuxe", "nfulye", "nfuxye", "nhule", "nhuxe", "nhulye", "nhuxye", "nnfe", "nnfye", "nnfule", "nnfuxe", "nnfulye", "nnfuxye", "nnhule", "nnhuxe", "nnhulye", "nnhuxye", "xnfe", "xnfye", "xnfule", "xnfuxe", "xnfulye", "xnfuxye", "xnhule", "xnhuxe", "xnhulye", "xnhuxye"],
    "んふょ": ["nfyo", "nfulyo", "nfuxyo", "nhulyo", "nhuxyo", "nnfyo", "nnfulyo", "nnfuxyo", "nnhulyo", "nnhuxyo", "xnfyo", "xnfulyo", "xnfuxyo", "xnhulyo", "xnhuxyo"],
    "んふぁ": ["nfa", "nfula", "nfuxa", "nhula", "nhuxa", "nnfa", "nnfula", "nnfuxa", "nnhula", "nnhuxa", "xnfa", "xnfula", "xnfuxa", "xnhula", "xnhuxa"],
    "んふぉ": ["nfo", "nfulo", "nfuxo", "nhulo", "nhuxo", "nnfo", "nnfulo", "nnfuxo", "nnhulo", "nnhuxo", "xnfo", "xnfulo", "xnfuxo", "xnhulo", "xnhuxo"],
    "んみゃ": ["nmya", "nmilya", "nmixya", "nnmya", "nnmilya", "nnmixya", "xnmya", "xnmilya", "xnmixya"],
    "んみぃ": ["nmyi", "nmili", "nmixi", "nmilyi", "nmixyi", "nnmyi", "nnmili", "nnmixi", "nnmilyi", "nnmixyi", "xnmyi", "xnmili", "xnmixi", "xnmilyi", "xnmixyi"],
    "んみゅ": ["nmyu", "nmilyu", "nmixyu", "nnmyu", "nnmilyu", "nnmixyu", "xnmyu", "xnmilyu", "xnmixyu"],
    "んみぇ": ["nmye", "nmile", "nmixe", "nmilye", "nmixye", "nnmye", "nnmile", "nnmixe", "nnmilye", "nnmixye", "xnmye", "xnmile", "xnmixe", "xnilye", "xnmixye"],
    "んみょ": ["nmyo", "nmilyo", "nmixyo", "nnmyo", "nnmilyo", "nnmixyo", "xnmyo", "xnmilyo", "xnmixyo"],
    "んりゃ": ["nrya", "nrilya", "nrixya", "nnrya", "nnrilya", "nnrixya", "xnrya", "xnrilya", "xnrixya"],
    "んりぃ": ["nryi", "nrili", "nrixi", "nrilyi", "nrixyi", "nnryi", "nnrili", "nnrixi", "nnrilyi", "nnrixyi", "xnryi", "xnrili", "xnrixi", "xnrilyi", "xnrixyi"],
    "んりゅ": ["nryu", "nrilyu", "nrixyu", "nnryu", "nnrilyu", "nnrixyu", "xnryu", "xnrilyu", "xnrixyu"],
    "んりぇ": ["nrye", "nrile", "nrixe", "nrilye", "nrixye", "nnrye", "nnrile", "nnrixe", "nnrilye", "nnrixye", "xnrye", "xnrile", "xnrixe", "xnrilye", "xnrixye"],
    "んりょ": ["nryo", "nrilyo", "nrixyo", "nnryo", "nnrilyo", "nnrixyo", "xnryo", "xnrilyo", "xnrixyo"],
    "んうぁ": ["nwha", "nula", "nuxa", "nwula", "nwuxa", "nwhula", "nwhuxa", "nnwha", "nnula", "nnuxa", "nnwula", "nnwuxa", "nnwhula", "nnwhuxa", "xnwha", "xnula", "xnuxa", "xnwula", "xnwuxa", "xnwhula", "xnwhuxa"],
    "んうぃ": ["nwi", "nwhi", "nuli", "nuxi", "nulyi", "nuxyi", "nwuli", "nwuxi", "nwulyi", "nwuxyi", "nwhuli", "nnwi", "nnwhi", "nnuli", "nnuxi", "nnulyi", "nnuxyi", "nnwuli", "nnwuxi", "nnwulyi", "nnwuxyi", "nnwhuli", "xnwi", "xnwhi", "xnuli", "xnuxi", "xnulyi", "xnuxyi", "xnwuli", "xnwuxi", "xnwulyi", "xnwuxyi", "xnwhuli"],
    "んうぇ": ["nwe", "nwhe", "nule", "nuxe", "nulye", "nuxye", "nwule", "nwuxe", "nwulye", "nwuxye", "nwhule", "nwhuxe", "nwhulye", "nwhuxye", "nnwe", "nnwhe", "nnule", "nnuxe", "nnulye", "nnuxye", "nnwule", "nnwuxe", "nnwulye", "nnwuxye", "nnwhule", "nnwhuxe", "nnwhulye", "nnwhuxye", "xnwe", "xnwhe", "xnule", "xnuxe", "xnulye", "xnuxye", "xnwule", "xnwuxe", "xnwulye", "xnwuxye", "xnwhule", "xnwhuxe", "xnwhulye", "xnwhuxye"],
    "んうぉ": ["nwho", "nulo", "nuxo", "nwulo", "nwuxo", "nwhulo", "nwhuxo", "nnwho", "nnulo", "nnuxo", "nnwulo", "nnwuxo", "nnwhulo", "nnwhuxo", "xnwho", "xnulo", "xnuxo", "xnwulo", "xnwuxo", "xnwhulo", "xnwhuxo"],
    "んゔぁ": ["nva", "nvula", "nvuxa", "nnva", "nnvula", "nnvuxa", "xnva", "xnvula", "xnvuxa"],
    "んゔぃ": ["nvi", "nvyi", "nvuli", "nvuxi", "nvulyi", "nvuxyi", "nnvi", "nnvyi", "nnvuli", "nnvuxi", "nnvulyi", "nnvuxyi", "xnvi", "xnvyi", "xnvuli", "xnvuxi", "xnvulyi", "xnvuxyi"],
    "んゔ": ["nvu", "nnvu", "xnvu"],
    "んゔぇ": ["nve", "nvye", "nvule", "nvuxe", "nvulye", "nvuxye", "nnve", "nnvye", "nnvule", "nnvuxe", "nnvulye", "nnvuxye", "xnve", "xnvye", "xnvule", "xnvuxe", "xnvulye", "xnvuxye"],
    "んゔぉ": ["nvo", "nvulo", "nvuxo", "nnvo", "nnvulo", "nnvuxo", "xnvo", "xnvulo", "xnvuxo"],
    "んゔゃ": ["nvya", "nvulya", "nvuxya", "nnvya", "nnvulya", "nnvuxya", "xnvya", "xnvulya", "xnvuxya"],
    "んゔゅ": ["nvyu", "nvulyu", "nvuxyu", "nnvyu", "nnvulyu", "nnvuxyu", "xnvyu", "xnvulyu", "xnvuxyu"],
    "んゔょ": ["nvyo", "nvulyo", "nvuxyo", "nnvyo", "nnvulyo", "nnvuxyo", "xnvyo", "xnvulyo", "xnvuxyo"],
    "んゐ": ["nwyi", "nnwyi", "xnwyi"],
    "んゑ": ["nwye", "nnwye", "xnwye"],
    "ん、": ["n,", "nn,", "xn,"],
    "っか": ["kka", "cca", "ltuka", "xtuka", "ltsuka", "xtsuka", "ltuca", "xtuca", "ltsuca", "xtsuca"],
    "っき": ["kki", "ltuki", "xtuki", "ltsuki", "xtsuki"],
    "っく": ["kku", "ccu", "ltuku", "xtuku", "ltsuku", "xtsuku", "ltucu", "xtucu", "ltsucu", "xtsucu"],
    "っけ": ["kke", "ltuke", "xtuke", "ltsuke", "xtsuke"],
    "っこ": ["kko", "cco", "ltuko", "xtuko", "ltsuko", "xtsuko", "ltuco", "xtuco", "ltsuco", "xtsuco"],
    "っさ": ["ssa", "ltusa", "xtusa", "ltsusa", "xtsusa"],
    "っし": ["ssi", "cci", "sshi", "ltusi", "xtsusi", "ltsusi", "xtsusi", "ltuci", "xtuci", "ltsuci", "xtsuci", "ltushi", "xtushi", "ltsushi", "xtsushi"],
    "っす": ["ssu", "ltusu", "xtusu", "ltsusu", "xtsusu"],
    "っせ": ["sse", "cce", "ltuse", "xtuse", "ltsuse", "xtsuse", "ltuce", "xtuce", "ltsuce", "xtsuce"],
    "っそ": ["sso", "ltuso", "xtuso", "ltsuso", "xtsuso"],
    "った": ["tta", "ltuta", "xtuta", "ltsuta", "xtsuta"],
    "っち": ["tti", "cchi", "ltuti", "xtuti", "ltsuti", "xtsuti", "ltuchi", "xtuchi", "ltsuchi", "xtsuchi"],
    "っつ": ["ttu", "ttsu", "ltutu", "xtutu", "ltsutu", "xtsutu", "ltutsu", "xtutsu", "ltsutsu", "xtsutsu"],
    "って": ["tte", "ltute", "xtute", "ltsute", "xtsute"],
    "っと": ["tto", "ltuto", "xtuto", "ltsuto", "xtsuto"],
    "っな": ["ltuna", "xtuna", "ltsuna", "xtsuna"],
    "っに": ["ltuni", "xtuni", "ltsuni", "xtsuni"],
    "っぬ": ["ltunu", "xtunu", "ltsunu", "xtsunu"],
    "っね": ["ltune", "xtune", "ltsune", "xtsune"],
    "っの": ["ltuno", "xtuno", "ltsuno", "xtsuno"],
    "っは": ["hha", "ltuha", "xtuha", "ltsuha", "xtsuha"],
    "っひ": ["hhi", "ltuhi", "xtuhi", "ltsuhi", "xtsuhi"],
    "っふ": ["ffu", "hhu", "ltufu", "xtufu", "ltsufu", "xtsufu", "ltuhu", "xtuhu", "ltsuhu", "xtsuhu"],
    "っへ": ["hhe", "ltuhe", "xtuhe", "ltsuhe", "xtsuhe"],
    "っほ": ["hho", "ltuho", "xtuho", "ltsuho", "xtsuho"],
    "っま": ["mma", "ltuma", "xtuma", "ltsuma", "xtsuma"],
    "っみ": ["mmi", "ltumi", "xtumi", "ltsumi", "xtsumi"],
    "っむ": ["mmu", "ltumu", "xtumu", "ltsumu", "xtsumu"],
    "っめ": ["mme", "ltume", "xtume", "ltsume", "xtsume"],
    "っも": ["mmo", "ltumo", "xtumo", "ltsumo", "xtsumo"],
    "っや": ["yya", "ltuya", "xtuya", "ltsuya", "xtsuya"],
    "っゆ": ["yyu", "ltuyu", "xtuyu", "ltsuyu", "xtsuyu"],
    "っよ": ["yyo", "ltuyo", "xtuyo", "ltsuyo", "xtsuyo"],
    "っら": ["rra", "ltura", "xtura", "ltsura", "xtsura"],
    "っり": ["rri", "lturi", "xturi", "ltsuri", "xtsuri"],
    "っる": ["rru", "lturu", "xturu", "ltsuru", "xtsuru"],
    "っれ": ["rre", "lture", "xture", "ltsure", "xtsure"],
    "っろ": ["rro", "lturo", "xturo", "ltsuro", "xtsuro"],
    "っわ": ["wwa", "ltuwa", "xtuwa", "ltsuwa", "xtsuwa"],
    "っを": ["wwo", "ltuwo", "xtuwo", "ltsuwo", "xtsuwo"],
    "っが": ["gga", "ltuga", "xtuga", "ltsuga", "xtsuga"],
    "っぎ": ["ggi", "ltugi", "xtugi", "ltsugi", "xtsugi"],
    "っぐ": ["ggu", "ltugu", "xtugu", "ltsugu", "xtsugu"],
    "っげ": ["gge", "ltuge", "xtuge", "ltsuge", "xtsuge"],
    "っご": ["ggo", "ltugo", "xtugo", "ltsugo", "xtsugo"],
    "っざ": ["zza", "ltuza", "xtuza", "ltsuza", "xtsuza"],
    "っじ": ["jji", "zzi", "ltuji", "xtuji", "ltsuji", "xtsuji", "ltuzi", "xtuzi", "ltsuzi", "xtsuzi"],
    "っず": ["zzu", "ltuzu", "xtuzu", "ltsuzu", "xtsuzu"],
    "っぜ": ["zze", "ltuze", "xtuze", "ltsuze", "xtsuze"],
    "っぞ": ["zzo", "ltuzo", "xtuzo", "ltsuzo", "xtsuzo"],
    "っだ": ["dda", "ltuda", "xtuda", "ltsuda", "xtsuda"],
    "っぢ": ["ddi", "ltudi", "xtudi", "ltsudi", "xtsudi"],
    "っづ": ["ddu", "ltudu", "xtudu", "ltsudu", "xtsudu"],
    "っで": ["dde", "ltude", "xtude", "ltsude", "xtsude"],
    "っど": ["ddo", "ltudo", "xtudo", "ltsudo", "xtsudo"],
    "っば": ["bba", "ltuba", "xtuba", "ltsuba", "xtsuba"],
    "っび": ["bbi", "ltubi", "xtubi", "ltsubi", "xtsubi"],
    "っぶ": ["bbu", "ltubu", "xtubu", "ltsubu", "xtsubu"],
    "っべ": ["bbe", "ltube", "xtube", "ltsube", "xtsube"],
    "っぼ": ["bbo", "ltubo", "xtubo", "ltsubo", "xtsubo"],
    "っぱ": ["ppa", "ltupa", "xtupa", "ltsupa", "xtsupa"],
    "っぴ": ["ppi", "ltupi", "xtupi", "ltsupi", "xtsupi"],
    "っぷ": ["ppu", "ltupu", "xtupu", "ltsupu", "xtsupu"],
    "っぺ": ["ppe", "ltupe", "xtupe", "ltsupe", "xtsupe"],
    "っぽ": ["ppo", "ltupo", "xtupo", "ltsupo", "xtsupo"],
    "っきゃ": ["kkya", "kkilya", "kkixya", "ltukya", "ltukilya", "ltukixya", "ltukya", "xtukilya", "xtukixya", "xtukya", "xtukilya", "ltsukixya", "ltsukya", "ltsukilya", "ltsukixya", "xtsukixya", "xtsukya", "xtsukilya", "xtsukixya"],
    "っきぃ": ["kkyi", "kkili", "kkilyi", "kkixi", "kkixyi", "ltukyi", "ltukili", "ltukilyi", "ltukixi", "ltukixyi", "xtukyi", "xtukili", "xtukilyi", "xtukixi", "xtukixyi", "ltsukyi", "ltsukili", "ltsukilyi", "ltsukixi", "ltsukixyi", "ltsukyi", "xtsukili", "xtsukilyi", "xtsukixi", "xtsukixyi"],
    "っきゅ": ["kkyu", "kkilyu", "kkixyu", "ltukyu", "ltukilyu", "ltukixyu", "xtukyu", "xtukilyu", "xtukixyu", "ltsukyu", "ltsukilyu", "ltsukixyu", "xtsukyu", "xtsukilyu", "xtsukixyu"],
    "っきょ": ["kkyo", "kkilyo", "kkixyo", "ltukyo", "xtukyo", "ltsukyo", "xtsukyo", "ltukilyo", "xtukilyo", "ltsukilyo", "xtsukilyo", "ltukixyo", "xtukixyo", "ltsukixyo", "xtsukixyo"],
    "っぎゃ": ["ggya", "ggilya", "ggixya", "ltugya", "xtugya", "ltsugya", "xtsugya", "ltugilya", "xtugilya", "ltsugilya", "xtsugilya", "ltugixya", "xtugixya", "ltsugixya", "xtsugixya"],
    "っぎゅ": ["ggyu", "ggilyu", "ggixyu", "ltugyu", "xtugyu", "ltsugyu", "xtsugyu", "ltugilyu", "xtugilyu", "ltsugilyu", "xtsugilyu", "ltugixyu", "xtugixyu", "ltsugixyu", "xtsugixyu"],
    "っぎょ": ["ggyo", "ggilyo", "ggixyo", "ltugyo", "xtugyo", "ltsugyo", "xtsugyo", "ltugilyo", "xtugilyo", "ltsugilyo", "xtsugilyo", "ltugixyo", "xtugixyo", "ltsugixyo", "xtsugixyo"],
    "っしゃ": ["ssya", "ssha", "ssilya", "ssixya", "sshilya", "sshixya", "ccilya", "ccixya", "ltusya", "xtusya", "ltsusya", "xtsusya", "ltusha", "xtusha", "ltsusha", "xtsusha", "ltusilya", "xtusilya", "ltsusilya", "xtsusilya", "ltusixya", "xtusixya", "ltsusixya", "xtsusixya", "ltushilya", "xtushilya", "ltsushilya", "xtsushilya", "ltushixya", "xtushixya", "ltsushixya", "xtsushixya", "ltucilya", "xtucilya", "ltsucilya", "xtsucilya", "ltucixya", "xtucixya", "ltsucixya", "xtsucixya"],
    "っしぃ": ["ssyi", "ssili", "ssixi", "ssilyi", "ssixyi", "sshili", "sshixi", "sshilyi", "sshixyi", "ccili", "ccixi", "ccilyi", "ccixyi", "ltusyi", "xtusyi", "ltsusyi", "xtsusyi", "ltusili", "xtusili", "ltsusili", "xtsusili", "ltusixi", "xtusixi", "ltsusixi", "xtsusixi", "ltusilyi", "xtusilyi", "ltsusilyi", "xtsusilyi", "ltusixyi", "xtusixyi", "ltsusixyi", "xtsusixyi", "ltushili", "xtushili", "ltsushili", "xtsushili", "ltushixi", "xtushixi", "ltsushixi", "xtsushixi", "ltushilyi", "xtushilyi", "ltsushilyi", "xtsushilyi", "ltushixyi", "xtushixyi", "ltsushixyi", "xtsushixyi", "ltucili", "xtucili", "ltsucili", "xtsucili", "ltucixi", "xtucixi", "ltsucixi", "xtsucixi", "ltucilyi", "xtucilyi", "ltsucilyi", "xtsucilyi", "ltucixyi", "xtucixyi", "ltsucixyi", "xtsucixyi"],
    "っしゅ": ["ssyu", "sshu", "ssilyu", "ssixyu", "sshilyu", "sshixyu", "ccilyu", "ccixyu", "ltusyu", "xtusyu", "ltsusyu", "xtsusyu", "ltushu", "xtushu", "ltsushu", "xtsushu", "ltusilyu", "xtusilyu", "ltsusilyu", "xtsusilyu", "ltusixyu", "xtusixyu", "ltsusixyu", "xtsusixyu", "ltushilyu", "xtushilyu", "ltsushilyu", "xtsushilyu", "ltushixyu", "xtushixyu", "ltsushixyu", "xtsushixyu", "ltucilyu", "xtucilyu", "ltsucilyu", "xtsucilyu", "ltucixyu", "xtucixyu", "ltsucixyu", "xtsucixyu"],
    "っしぇ": ["ssye", "sshe", "ssile", "ssilye", "ssixe", "ssixye", "sshile", "sshilye", "sshixe", "sshixye", "ccile", "ccilye", "ccixe", "ccixye", "ltusye", "xtusye", "ltsusye", "xtsusye", "ltushe", "xtushe", "ltsushe", "xtsushe", "ltusile", "xtusile", "ltsusile", "xtsusile", "ltusilye", "xtusilye", "ltsusilye", "xtsusilye", "ltusixe", "xtusixe", "ltsusixe", "xtsusixe", "ltusixye", "xtusixye", "ltsusixye", "xtsusixye", "ltushile", "xtushile", "ltsushile", "xtsushile", "ltushilye", "xtushilye", "ltsushilye", "xtsushilye", "ltushixe", "xtushixe", "ltsushixe", "xtsushixe", "ltushixye", "xtushixye", "ltsushixye", "xtsushixye", "ltucile", "xtucile", "ltsucile", "xtsucile", "ltucilye", "xtucilye", "ltsucilye", "xtsucilye", "ltucixe", "xtucixe", "ltsucixe", "xtsucixe", "ltucixye", "xtucixye", "ltsucixye", "xtsucixye"],
    "っしょ": ["ssyo", "ssho", "ssilyo", "ssixyo", "sshilyo", "sshixyo", "ccilyo", "ccixyo", "ltusyo", "xtusyo", "ltsusyo", "xtsusyo", "ltusho", "xtusho", "ltsusho", "xtsusho", "ltusilyo", "xtusilyo", "ltsusilyo", "xtsusilyo", "ltusixyo", "xtusixyo", "ltsusixyo", "xtsusixyo", "ltushilyo", "xtushilyo", "ltsushilyo", "xtsushilyo", "ltushixyo", "xtushixyo", "ltsushixyo", "xtsushixyo", "ltucilyo", "xtucilyo", "ltsucilyo", "xtsucilyo", "ltucixyo", "xtucixyo", "ltsucixyo", "xtsucixyo"],
    "っじゃ": ["jja", "jjya", "zzya", "jjilya", "jjixya", "zzilya", "zzixya", "ltuja", "xtuja", "ltsuja", "xtsuja", "ltujya", "xtujya", "ltsujya", "xtsujya", "ltuzya", "xtuzya", "ltsuzya", "xtsuzya", "ltujilya", "xtujilya", "ltsujilya", "xtsujilya", "ltujixya", "xtujixya", "ltsujixya", "xtsujixya", "ltuzilya", "xtuzilya", "ltsuzilya", "xtsuzilya", "ltuzixya", "xtuzixya", "ltsuzixya", "xtsuzixya"],
    "っじぃ": ["jjyi", "zzyi", "jjili", "jjixi", "jjilyi", "jjixyi", "zzili", "zzixi", "zzilyi", "zzixyi", "ltujyi", "xtujyi", "ltsujyi", "xtsujyi", "ltuzyi", "xtuzyi", "ltsuzyi", "xtsuzyi", "ltujili", "xtujili", "ltsujili", "xtsujili", "ltujixi", "xtujixi", "ltsujixi", "xtsujixi", "ltujilyi", "xtujilyi", "ltsujilyi", "xtsujilyi", "ltujixyi", "xtujixyi", "ltsujixyi", "xtsujixyi", "ltuzili", "xtuzili", "ltsuzili", "xtsuzili", "ltuzixi", "xtuzixi", "ltsuzixi", "xtsuzixi", "ltuzilyi", "xtuzilyi", "ltsuzilyi", "xtsuzilyi", "ltuzixyi", "xtuzixyi", "ltsuzixyi", "xtsuzixyi"],
    "っじゅ": ["jju", "jjyu", "zzyu", "jjilyu", "jjixyu", "zzilyu", "zzixyu", "ltuju", "xtuju", "ltsuju", "xtsuju", "ltujyu", "xtujyu", "ltsujyu", "xtsujyu", "ltuzyu", "xtuzyu", "ltsuzyu", "xtsuzyu", "ltujilyu", "xtujilyu", "ltsujilyu", "xtsujilyu", "ltujixyu", "xtujixyu", "ltsujixyu", "xtsujixyu", "ltuzilyu", "xtuzilyu", "ltsuzilyu", "xtsuzilyu", "ltuzixyu", "xtuzixyu", "ltsuzixyu", "xtsuzixyu"],
    "っじぇ": ["jje", "jjye", "zzye", "jjile", "jjixe", "jjilye", "jjixye", "zzile", "zzixe", "zzilye", "zzixye", "ltuje", "xtuje", "ltsuje", "xtsuje", "ltujye", "xtujye", "ltsujye", "xtsujye", "ltuzye", "xtuzye", "ltsuzye", "xtsuzye", "ltujile", "xtujile", "ltsujile", "xtsujile", "ltujixe", "xtujixe", "ltsujixe", "xtsujixe", "ltujilye", "xtujilye", "ltsujilye", "xtsujilye", "ltujixye", "xtujixye", "ltsujixye", "xtsujixye", "ltuzile", "xtuzile", "ltsuzile", "xtsuzile", "ltuzixe", "xtuzixe", "ltsuzixe", "xtsuzixe", "ltuzilye", "xtuzilye", "ltsuzilye", "xtsuzilye", "ltuzixye", "xtuzixye", "ltsuzixye", "xtsuzixye"],
    "っじょ": ["jjo", "jjyo", "zzyo", "jjilyo", "jjixyo", "zzilyo", "zzixyo", "ltujo", "xtujo", "ltsujo", "xtsujo", "ltujyo", "xtujyo", "ltsujyo", "xtsujyo", "ltuzyo", "xtuzyo", "ltsuzyo", "xtsuzyo", "ltujilyo", "xtujilyo", "ltsujilyo", "xtsujilyo", "ltujixyo", "xtujixyo", "ltsujixyo", "xtsujixyo", "ltuzilyo", "xtuzilyo", "ltsuzilyo", "xtsuzilyo", "ltuzixyo", "xtuzixyo", "ltsuzixyo", "xtsuzixyo"],
    "っちゃ": ["ttya", "ccha", "ccya", "ttilya", "ttixya", "cchilya", "cchixya", "ltutya", "xtutya", "ltsutya", "xtsutya", "ltucha", "xtucha", "ltsucha", "xtsucha", "ltucya", "xtucya", "ltsucya", "xtsucya", "ltutilya", "xtutilya", "ltsutilya", "xtsutilya", "ltutixya", "xtutixya", "ltsutixya", "xtsutixya", "ltuchilya", "xtuchilya", "ltsuchilya", "xtsuchilya", "ltuchixya", "xtuchixya", "ltsuchixya", "xtsuchixya"],
    "っちぃ": ["ttyi", "ccyi", "ttili", "ttixi", "ttilyi", "ttixyi", "cchili", "cchixi", "cchilyi", "cchixyi", "ltutyi", "xtutyi", "ltsutyi", "xtsutyi", "ltucyi", "xtucyi", "ltsucyi", "xtsucyi", "ltutili", "xtutili", "ltsutili", "xtsutili", "ltutixi", "xtutixi", "ltsutixi", "xtsutixi", "ltutilyi", "xtutilyi", "ltsutilyi", "xtsutilyi", "ltutixyi", "xtutixyi", "ltsutixyi", "xtsutixyi", "ltuchili", "xtuchili", "ltsuchili", "xtsuchili", "ltuchixi", "xtuchixi", "ltsuchixi", "xtsuchixi", "ltuchilyi", "xtuchilyi", "ltsuchilyi", "xtsuchilyi", "ltuchixyi", "xtuchixyi", "ltsuchixyi", "xtsuchixyi"],
    "っちゅ": ["ttyu", "cchu", "ccyu", "ttilyu", "ttixyu", "cchilyu", "cchixyu", "ltutyu", "xtutyu", "ltsutyu", "xtsutyu", "ltuchu", "xtuchu", "ltsuchu", "xtsuchu", "ltucyu", "xtucyu", "ltsucyu", "xtsucyu", "ltutilyu", "xtutilyu", "ltsutilyu", "xtsutilyu", "ltutixyu", "xtutixyu", "ltsutixyu", "xtsutixyu", "ltuchilyu", "xtuchilyu", "ltsuchilyu", "xtsuchilyu", "ltuchixyu", "xtuchixyu", "ltsuchixyu", "xtsuchixyu"],
    "っちぇ": ["ttye", "cche", "ccye", "ttile", "ttixe", "ttilye", "ttixye", "cchile", "cchixe", "cchilye", "cchixye", "ltutye", "xtutye", "ltsutye", "xtsutye", "ltuche", "xtuche", "ltsuche", "xtsuche", "ltucye", "xtucye", "ltsucye", "xtsucye", "ltutile", "xtutile", "ltsutile", "xtsutile", "ltutixe", "xtutixe", "ltsutixe", "xtsutixe", "ltutilye", "xtutilye", "ltsutilye", "xtsutilye", "ltutixye", "xtutixye", "ltsutixye", "xtsutixye", "ltuchile", "xtuchile", "ltsuchile", "xtsuchile", "ltuchixe", "xtuchixe", "ltsuchixe", "xtsuchixe", "ltuchilye", "xtuchilye", "ltsuchilye", "xtsuchilye", "ltuchixye", "xtuchixye", "ltsuchixye", "xtsuchixye"],
    "っちょ": ["ttyo", "ccho", "ccyo", "ttilyo", "ttixyo", "cchilyo", "cchixyo", "ltutyo", "xtutyo", "ltsutyo", "xtsutyo", "ltucho", "xtucho", "ltsucho", "xtsucho", "ltucyo", "xtucyo", "ltsucyo", "xtsucyo", "ltutilyo", "xtutilyo", "ltsutilyo", "xtsutilyo", "ltutixyo", "xtutixyo", "ltsutixyo", "xtsutixyo", "ltuchilyo", "xtuchilyo", "ltsuchilyo", "xtsuchilyo", "ltuchixyo", "xtuchixyo", "ltsuchixyo", "xtsuchixyo"],
    "っぢゃ": ["ddya", "ddilya", "ddixya", "ltudya", "xtudya", "ltsudya", "xtsudya", "ltudilya", "xtudilya", "ltsudilya", "xtsudilya", "ltudixya", "xtudixya", "ltsudixya", "xtsudixya"],
    "っぢゅ": ["ddyu", "ddilyu", "ddixyu", "ltudyu", "xtudyu", "ltsudyu", "xtsudyu", "ltudilyu", "xtudilyu", "ltsudilyu", "xtsudilyu", "ltudixyu", "xtudixyu", "ltsudixyu", "xtsudixyu"],
    "っぢぇ": ["ddye", "ddile", "ddixe", "ddilye", "ddixye", "ltudye", "xtudye", "ltsudye", "xtsudye", "ltudile", "xtudile", "ltsudile", "xtsudile", "ltudixe", "xtudixe", "ltsudixe", "xtsudixe", "ltudilye", "xtudilye", "ltsudilye", "xtsudilye", "ltudixye", "xtudixye", "ltsudixye", "xtsudixye"],
    "っぢょ": ["ddyo", "ddilyo", "ddixyo", "ltudyo", "xtudyo", "ltsudyo", "xtsudyo", "ltudilyo", "xtudilyo", "ltsudilyo", "xtsudilyo", "ltudixyo", "xtudixyo", "ltsudixyo", "xtsudixyo"],
    "っつぁ": ["ttsa", "ttula", "ttuxa", "ttsula", "ttsuxa", "ltutsa", "xtutsa", "ltsutsa", "xtsutsa", "ltutula", "xtutula", "ltsutula", "xtsutula", "ltutuxa", "xtutuxa", "ltsutuxa", "xtsutuxa", "ltutsula", "xtutsula", "ltsutsula", "xtsutsula", "ltutsuxa", "xtutsuxa", "ltsutsuxa", "xtsutsuxa"],
    "っつぃ": ["ttsi", "ttuli", "ttuxi", "ttulyi", "ttuxyi", "ttsuli", "ttsuxi", "ttsulyi", "ttsuxyi", "ltutsi", "xtutsi", "ltsutsi", "xtsutsi", "ltutuli", "xtutuli", "ltsutuli", "xtsutuli", "ltutuxi", "xtutuxi", "ltsutuxi", "xtsutuxi", "ltutulyi", "xtutulyi", "ltsutulyi", "xtsutulyi", "ltutuxyi", "xtutuxyi", "ltsutuxyi", "xtsutuxyi", "ltutsuli", "xtutsuli", "ltsutsuli", "xtsutsuli", "ltutsuxi", "xtutsuxi", "ltsutsuxi", "xtsutsuxi", "ltutsulyi", "xtutsulyi", "ltsutsulyi", "xtsutsulyi", "ltutsuxyi", "xtutsuxyi", "ltsutsuxyi", "xtsutsuxyi"],
    "っつぇ": ["ttse", "ttule", "ttuxe", "ttulye", "ttuxye", "ttsule", "ttsuxe", "ttsulye", "ttsuxye", "ltutse", "xtutse", "ltsutse", "xtsutse", "ltutule", "xtutule", "ltsutule", "xtsutule", "ltutuxe", "xtutuxe", "ltsutuxe", "xtsutuxe", "ltutulye", "xtutulye", "ltsutulye", "xtsutulye", "ltutuxye", "xtutuxye", "ltsutuxye", "xtsutuxye", "ltutsule", "xtutsule", "ltsutsule", "xtsutsule", "ltutsuxe", "xtutsuxe", "ltsutsuxe", "xtsutsuxe", "ltutsulye", "xtutsulye", "ltsutsulye", "xtsutsulye", "ltutsuxye", "xtutsuxye", "ltsutsuxye", "xtsutsuxye"],
    "っつぉ": ["ttso", "ttulo", "ttuxo", "ttsulo", "ttsuxo", "ltutso", "xtutso", "ltsutso", "xtsutso", "ltutulo", "xtutulo", "ltsutulo", "xtsutulo", "ltutuxo", "xtutuxo", "ltsutuxo", "xtsutuxo", "ltutsulo", "xtutsulo", "ltsutsulo", "xtsutsulo", "ltutsuxo", "xtutsuxo", "ltsutsuxo", "xtsutsuxo"],
    "ってゃ": ["ttha", "ttelya", "ttexya", "ltutha", "xtutha", "ltsutha", "xtsutha", "ltutelya", "xtutelya", "ltsutelya", "xtsutelya", "ltutexya", "xtutexya", "ltsutexya", "xtsutexya"],
    "ってぃ": ["tthi", "tteli", "ttexi", "ttelyi", "ttexyi", "ltuthi", "xtuthi", "ltsuthi", "xtsuthi", "ltuteli", "xtuteli", "ltsuteli", "xtsuteli", "ltutexi", "xtutexi", "ltsutexi", "xtsutexi", "ltutelyi", "xtutelyi", "ltsutelyi", "xtsutelyi", "ltutexyi", "xtutexyi", "ltsutexyi", "xtsutexyi"],
    "ってゅ": ["tthu", "ttelyu", "ttexyu", "ltuthu", "xtuthu", "ltsuthu", "xtsuthu", "ltutelyu", "xtutelyu", "ltsutelyu", "xtsutelyu", "ltutexyu", "xtutexyu", "ltsutexyu", "xtsutexyu"],
    "ってぇ": ["tthe", "ttele", "ttexe", "ttelye", "ttexye", "ltuthe", "xtuthe", "ltsuthe", "xtsuthe", "ltutele", "xtutele", "ltsutele", "xtsutele", "ltutexe", "xtutexe", "ltsutexe", "xtsutexe", "ltutelye", "xtutelye", "ltsutelye", "xtsutelye", "ltutexye", "xtutexye", "ltsutexye", "xtsutexye"],
    "ってょ": ["ttho", "ttelyo", "ttexyo", "ltutho", "xtutho", "ltsutho", "xtsutho", "ltutelyo", "xtutelyo", "ltsutelyo", "xtsutelyo", "ltutexyo", "xtutexyo", "ltsutexyo", "xtsutexyo"],
    "っでゃ": ["ddha", "ddelya", "ddexya", "ltudha", "xtudha", "ltsudha", "xtsudha", "ltudelya", "xtudelya", "ltsudelya", "xtsudelya", "ltudexya", "xtudexya", "ltsudexya", "xtsudexya"],
    "っでぃ": ["ddhi", "ddeli", "ddexi", "ddelyi", "ddexyi", "ltudhi", "xtudhi", "ltsudhi", "xtsudhi", "ltudeli", "xtudeli", "ltsudeli", "xtsudeli", "ltudexi", "xtudexi", "ltsudexi", "xtsudexi", "ltudelyi", "xtudelyi", "ltsudelyi", "xtsudelyi", "ltudexyi", "xtudexyi", "ltsudexyi", "xtsudexyi"],
    "っでゅ": ["ddhu", "ddelyu", "ddexyu", "ltudhu", "xtudhu", "ltsudhu", "xtsudhu", "ltudelyu", "xtudelyu", "ltsudelyu", "xtsudelyu", "ltudexyu", "xtudexyu", "ltsudexyu", "xtsudexyu"],
    "っでぇ": ["ddhe", "ddele", "ddexe", "ddelye", "ddexye", "ltudhe", "xtudhe", "ltsudhe", "xtsudhe", "ltudele", "xtudele", "ltsudele", "xtsudele", "ltudexe", "xtudexe", "ltsudexe", "xtsudexe", "ltudelye", "xtudelye", "ltsudelye", "xtsudelye", "ltudexye", "xtudexye", "ltsudexye", "xtsudexye"],
    "っでょ": ["ddho", "ddelyo", "ddexyo", "ltudho", "xtudho", "ltsudho", "xtsudho", "ltudelyo", "xtudelyo", "ltsudelyo", "xtsudelyo", "ltudexyo", "xtudexyo", "ltsudexyo", "xtsudexyo"],
    "っぴゃ": ["ppya", "ppilya", "ppixya", "ltupya", "xtupya", "ltsupya", "xtsupya", "ltupilya", "xtupilya", "ltsupilya", "xtsupilya", "ltupixya", "xtupixya", "ltsupixya", "xtsupixya"],
    "っぴぃ": ["ppyi", "ppili", "ppixi", "ppilyi", "ppixyi", "ltupyi", "xtupyi", "ltsupyi", "xtsupyi", "ltupili", "xtupili", "ltsupili", "xtsupili", "ltupixi", "xtupixi", "ltsupixi", "xtsupixi", "ltupilyi", "xtupilyi", "ltsupilyi", "xtsupilyi", "ltupixyi", "xtupixyi", "ltsupixyi", "xtsupixyi"],
    "っぴゅ": ["ppyu", "ppilyu", "ppixyu", "ltupyu", "xtupyu", "ltsupyu", "xtsupyu", "ltupilyu", "xtupilyu", "ltsupilyu", "xtsupilyu", "ltupixyu", "xtupixyu", "ltsupixyu", "xtsupixyu"],
    "っぴぇ": ["ppye", "ppile", "ppixe", "ppilye", "ppixye", "ltupye", "xtupye", "ltsupye", "xtsupye", "ltupile", "xtupile", "ltsupile", "xtsupile", "ltupixe", "xtupixe", "ltsupixe", "xtsupixe", "ltupilye", "xtupilye", "ltsupilye", "xtsupilye", "ltupixye", "xtupixye", "ltsupixye", "xtsupixye"],
    "っぴょ": ["ppyo", "ppilyo", "ppixyo", "ltupyo", "xtupyo", "ltsupyo", "xtsupyo", "ltupilyo", "xtupilyo", "ltsupilyo", "xtsupilyo", "ltupixyo", "xtupixyo", "ltsupixyo", "xtsupixyo"],
    "っひゃ": ["hhya", "hhilya", "hhixya", "ltuhya", "xtuhya", "ltsuhya", "xtsuhya", "ltuhilya", "xtuhilya", "ltsuhilya", "xtsuhilya", "ltuhixya", "xtuhixya", "ltsuhixya", "xtsuhixya"],
    "っひぃ": ["hhyi", "hhili", "hhixi", "hhilyi", "hhixyi", "ltuhyi", "xtuhyi", "ltsuhyi", "xtsuhyi", "ltuhili", "xtuhili", "ltsuhili", "xtsuhili", "ltuhixi", "xtuhixi", "ltsuhixi", "xtsuhixi", "ltuhilyi", "xtuhilyi", "ltsuhilyi", "xtsuhilyi", "ltuhixyi", "xtuhixyi", "ltsuhixyi", "xtsuhixyi"],
    "っひゅ": ["hhyu", "hhilyu", "hhixyu", "ltuhyu", "xtuhyu", "ltsuhyu", "xtsuhyu", "ltuhilyu", "xtuhilyu", "ltsuhilyu", "xtsuhilyu", "ltuhixyu", "xtuhixyu", "ltsuhixyu", "xtsuhixyu"],
    "っひぇ": ["hhye", "hhile", "hhixe", "hhilye", "hhixye", "ltuhye", "xtuhye", "ltsuhye", "xtsuhye", "ltuhile", "xtuhile", "ltsuhile", "xtsuhile", "ltuhixe", "xtuhixe", "ltsuhixe", "xtsuhixe", "ltuhilye", "xtuhilye", "ltsuhilye", "xtsuhilye", "ltuhixye", "xtuhixye", "ltsuhixye", "xtsuhixye"],
    "っひょ": ["hhyo", "hhilyo", "hhixyo", "ltuhyo", "xtuhyo", "ltsuhyo", "xtsuhyo", "ltuhilyo", "xtuhilyo", "ltsuhilyo", "xtsuhilyo", "ltuhixyo", "xtuhixyo", "ltsuhixyo", "xtsuhixyo"],
    "っびゃ": ["bbya", "bbilya", "bbixya", "ltubya", "xtubya", "ltsubya", "xtsubya", "ltubilya", "xtubilya", "ltsubilya", "xtsubilya", "ltubixya", "xtubixya", "ltsubixya", "xtsubixya"],
    "っびぃ": ["bbyi", "bbili", "bbixi", "bbilyi", "bbixyi", "ltubyi", "xtubyi", "ltsubyi", "xtsubyi", "ltubili", "xtubili", "ltsubili", "xtsubili", "ltubixi", "xtubixi", "ltsubixi", "xtsubixi", "ltubilyi", "xtubilyi", "ltsubilyi", "xtsubilyi", "ltubixyi", "xtubixyi", "ltsubixyi", "xtsubixyi"],
    "っびゅ": ["bbyu", "bbilyu", "bbixyu", "ltubyu", "xtubyu", "ltsubyu", "xtsubyu", "ltubilyu", "xtubilyu", "ltsubilyu", "xtsubilyu", "ltubixyu", "xtubixyu", "ltsubixyu", "xtsubixyu"],
    "っびぇ": ["bbye", "bbile", "bbixe", "bbilye", "bbixye", "ltubye", "xtubye", "ltsubye", "xtsubye", "ltubile", "xtubile", "ltsubile", "xtsubile", "ltubixe", "xtubixe", "ltsubixe", "xtsubixe", "ltubilye", "xtubilye", "ltsubilye", "xtsubilye", "ltubixye", "xtubixye", "ltsubixye", "xtsubixye"],
    "っびょ": ["bbyo", "bbilyo", "bbixyo", "ltubyo", "xtubyo", "ltsubyo", "xtsubyo", "ltubilyo", "xtubilyo", "ltsubilyo", "xtsubilyo", "ltubixyo", "xtubixyo", "ltsubixyo", "xtsubixyo"],
    "っふぁ": ["ffa", "ffula", "ffuxa", "hhula", "hhuxa", "ltufa", "xtufa", "ltsufa", "xtsufa", "ltufula", "xtufula", "ltsufula", "xtsufula", "ltufuxa", "xtufuxa", "ltsufuxa", "xtsufuxa", "ltuhula", "xtuhula", "ltsuhula", "xtsuhula", "ltuhuxa", "xtuhuxa", "ltsuhuxa", "xtsuhuxa"],
    "っふぃ": ["ffi", "ffyi", "ffuli", "ffuxi", "ffulyi", "ffuxyi", "hhuli", "hhuxi", "hhulyi", "hhuxyi", "ltufi", "xtufi", "ltsufi", "xtsufi", "ltufyi", "xtufyi", "ltsufyi", "xtsufyi", "ltufuli", "xtufuli", "ltsufuli", "xtsufuli", "ltufuxi", "xtufuxi", "ltsufuxi", "xtsufuxi", "ltufulyi", "xtufulyi", "ltsufulyi", "xtsufulyi", "ltufuxyi", "xtufuxyi", "ltsufuxyi", "xtsufuxyi", "ltuhuli", "xtuhuli", "ltsuhuli", "xtsuhuli", "ltuhuxi", "xtuhuxi", "ltsuhuxi", "xtsuhuxi", "ltuhulyi", "xtuhulyi", "ltsuhulyi", "xtsuhulyi", "ltuhuxyi", "xtuhuxyi", "ltsuhuxyi", "xtsuhuxyi"],
    "っふぇ": ["ffe", "ffye", "ffule", "ffuxe", "ffulye", "ffuxye", "hhule", "hhuxe", "hhulye", "hhuxye", "ltufe", "xtufe", "ltsufe", "xtsufe", "ltufye", "xtufye", "ltsufye", "xtsufye", "ltufule", "xtufule", "ltsufule", "xtsufule", "ltufuxe", "xtufuxe", "ltsufuxe", "xtsufuxe", "ltufulye", "xtufulye", "ltsufulye", "xtsufulye", "ltufuxye", "xtufuxye", "ltsufuxye", "xtsufuxye", "ltuhule", "xtuhule", "ltsuhule", "xtsuhule", "ltuhuxe", "xtuhuxe", "ltsuhuxe", "xtsuhuxe", "ltuhulye", "xtuhulye", "ltsuhulye", "xtsuhulye", "ltuhuxye", "xtuhuxye", "ltsuhuxye", "xtsuhuxye"],
    "っふぉ": ["ffo", "ffulo", "ffuxo", "hhulo", "hhuxo", "ltufo", "xtufo", "ltsufo", "xtsufo", "ltufulo", "xtufulo", "ltsufulo", "xtsufulo", "ltufuxo", "xtufuxo", "ltsufuxo", "xtsufuxo", "ltuhulo", "xtuhulo", "ltsuhulo", "xtsuhulo", "ltuhuxo", "xtuhuxo", "ltsuhuxo", "xtsuhuxo"],
    "っみゃ": ["mmya", "mmilya", "mmixya", "ltumya", "xtumya", "ltsumya", "xtsumya", "ltumilya", "xtumilya", "ltsumilya", "xtsumilya", "ltumixya", "xtumixya", "ltsumixya", "xtsumixya"],
    "っみぃ": ["mmyi", "mmili", "mmixi", "mmilyi", "mmixyi", "ltumyi", "xtumyi", "ltsumyi", "xtsumyi", "ltumili", "xtumili", "ltsumili", "xtsumili", "ltumixi", "xtumixi", "ltsumixi", "xtsumixi", "ltumilyi", "xtumilyi", "ltsumilyi", "xtsumilyi", "ltumixyi", "xtumixyi", "ltsumixyi", "xtsumixyi"],
    "っみゅ": ["mmyu", "mmilyu", "mmixyu", "ltumyu", "xtumyu", "ltsumyu", "xtsumyu", "ltumilyu", "xtumilyu", "ltsumilyu", "xtsumilyu", "ltumixyu", "xtumixyu", "ltsumixyu", "xtsumixyu"],
    "っみぇ": ["mmye", "mmile", "mmixe", "mmilye", "mmixye", "ltumye", "xtumye", "ltsumye", "xtsumye", "ltumile", "xtumile", "ltsumile", "xtsumile", "ltumixe", "xtumixe", "ltsumixe", "xtsumixe", "ltumilye", "xtumilye", "ltsumilye", "xtsumilye", "ltumixye", "xtumixye", "ltsumixye", "xtsumixye"],
    "っみょ": ["mmyo", "mmilyo", "mmixyo", "ltumyo", "xtumyo", "ltsumyo", "xtsumyo", "ltumilyo", "xtumilyo", "ltsumilyo", "xtsumilyo", "ltumixyo", "xtumixyo", "ltsumixyo", "xtsumixyo"],
    "っりゃ": ["rrya", "rrilya", "rrixya", "lturya", "xturya", "ltsurya", "xtsurya", "lturilya", "xturilya", "ltsurilya", "xtsurilya", "lturixya", "xturixya", "ltsurixya", "xtsurixya"],
    "っりぃ": ["rryi", "rrili", "rrixi", "rrilyi", "rrixyi", "lturyi", "xturyi", "ltsuryi", "xtsuryi", "lturili", "xturili", "ltsurili", "xtsurili", "lturixi", "xturixi", "ltsurixi", "xtsurixi", "lturilyi", "xturilyi", "ltsurilyi", "xtsurilyi", "lturixyi", "xturixyi", "ltsurixyi", "xtsurixyi"],
    "っりゅ": ["rryu", "rrilyu", "rrixyu", "lturyu", "xturyu", "ltsuryu", "xtsuryu", "lturilyu", "xturilyu", "ltsurilyu", "xtsurilyu", "lturixyu", "xturixyu", "ltsurixyu", "xtsurixyu"],
    "っりぇ": ["rrye", "rrile", "rrixe", "rrilye", "rrixye", "lturye", "xturye", "ltsurye", "xtsurye", "lturile", "xturile", "ltsurile", "xtsurile", "lturixe", "xturixe", "ltsurixe", "xtsurixe", "lturilye", "xturilye", "ltsurilye", "xtsurilye", "lturixye", "xturixye", "ltsurixye", "xtsurixye"],
    "っりょ": ["rryo", "rrilyo", "rrixyo", "lturyo", "xturyo", "ltsuryo", "xtsuryo", "lturilyo", "xturilyo", "ltsurilyo", "xtsurilyo", "lturixyo", "xturixyo", "ltsurixyo", "xtsurixyo"],
    "!": ["!"],
    "?": ["?"],
    "ー": ["-"],
    ",": [","],
    "、": [","]
}
